language: ruby
sudo: false
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.4
  - 2.3.7

gemfile:
  - Gemfile
  - Gemfiles/Gemfile.jmenji
  - Gemfiles/Gemfile.mentioji

script:
  - bundle exec jekyll build
  - ruby script/generated_post_body.rb
