language: ruby
sudo: false
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7

gemfile:
  - Gemfile
  - Gemfiles/jemoji.gemfile
  - Gemfiles/jmentions.gemfile
  - Gemfiles/jmenji.gemfile
  - Gemfiles/mentioji.gemfile

script:
  - bundle exec jekyll build
  - ruby script/generated_post_body.rb
