language: ruby
sudo: false
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7

gemfile:
  - Gemfile
  - Gemfiles/Gemfile.jemoji
  - Gemfiles/Gemfile.jemoji_improved
  - Gemfiles/Gemfile.jmentions
  - Gemfiles/Gemfile.jmentions_improved
  - Gemfiles/Gemfile.jmenji
  - Gemfiles/Gemfile.jmenji_improved
  - Gemfiles/Gemfile.mentioji

script:
  - bundle exec jekyll build
  - ruby script/generated_post_body.rb
