title: 1000Posts
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This site contains 1000 posts each containing multiple paragraphs
  with mentions and emoji sprinkled amongst them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
